config/routes.rb
Databox::Application.routes.draw do

  match "admin_customers" => "customers#admin_customers"
  post "admin_customers_next_page" => "customers#next_page"
  post "admin_customers_previous_page" => "customers#previous_page"
  get "search_customer" => "customers#search_customer"
  get "admin_customers_detail" => "customers#admin_customers_detail"
  
   get "products/overview/:id" => "products#overview"
   
   get "facility/control/main" => "facilities#main"
   post "facility/control/EditFacility" => "facilities#edit"
   post "facility/control/UpdateFacility" => "facilities#update"
   get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
   

 get "facility/control/main" => "facilities#main"
 post "facility/control/EditFacility" => "facilities#edit"
 post "facility/control/UpdateFacility" => "facilities#update"
 get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
 
 match "facility/:facility_id/inventory" => "pages#facility_inventory", as: :facility_inventory
 match "facility/edit_facility" => "pages#edit_facility", as: :edit_facility
 match "facility/selection" => "pages#facility_selection", as: :facility_selection
 match "facility/verify_pick" => "pages#verify_pick", as: :verify_pick
 match "facility/returns/receive" => "pages#receive_return", as: :receive_return
 match "facility/inventory/receive" => "pages#receive_inventory", as: :receive_inventory
 match "facility/pick_move_stock" => "pages#pick_move_stock", as: :pick_move_stock
 match "facility/picklist_options" => "pages#picklist_options", as: :picklist_options
 match "facility/picklist_manage" => "pages#picklist_manage", as: :picklist_manage
 match "facility/pack_order" => "pages#pack_order", as: :pack_order
 match "facility/inventory/transfers" => "pages#facility_transfers", as: :facility_transfers
 match "facility/facility_location" => "pages#facility_location", as: :facility_location
 match "facility/edit_inventory_item_details" => "pages#edit_inventory_item_details", as: :edit_inventory_item_details
 match "facility/edit_facility_location_details" => "pages#edit_facility_location_details", as: :edit_facility_location_details
 match "facility/edit_facility_inventory_items" => "pages#edit_facility_inventory_items", as: :edit_facility_inventory_items

  match "users/sign_up" => "pages#error"

  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations', :sessions => "users/sessions"},
  :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock'}
  devise_scope :user do
    match "party/" => "users/users#index"
    match "party/adduser" => "users/users#adduser"
    post "party/adduser"
    match "party/status" => "users/users#status"
    match "party/update_user" => "users/users#update_user"
    match "party/assign_role" => "users/users#assign_role"
    match "/users/check_email" => "users/users#check_email"
  end
  root :to => 'products#index'

  put "admins/update_user"
  put "admins/assign_role"

  get "pages/error"

  resources :products do
    collection do
      post :update_image
      post :update_product
      post :update_factory
      get :overview
      get :copy
      get :color
      match "weight_size/:sku" => "products#weight_size", as: :weight_size
      match "pricing/:sku" => "products#pricing", as: :pricing
      match "photos/:sku" => "products#photos", as: :photo
      get :moq_cost
      get :child
      get :find
      post  :results
    end
  end

  resources :product_promotions do
    collection do
      post :promotions_per_page
      post :delete_promotions
      get :stores
      post :stores_per_page
      post :delete_stores
      post :update_stores
      post :insert_stores

    end
  end

  resources :promotion_codes do
    collection do
      post :promotion_codes_per_page
      post :delete_promotion_codes
      get :mass_insert
      post :mass_insert
      post :add_email
      post :add_party
      post :delete_email
      post :delete_party
      post :check_party_id
    end
  end

  namespace :facility do
    resources :ship_rates do
      collection do
        post :get_for_country
        post :get_rates
        post :get_for_city_autocomplete
        post :shipment_per_page
        post :delete_shipment
        post :update_shipment
        post :get_quote
        post :get_for_country_autocomplete
        get :estimate
      end
    end
  end
  resources :return_headers do
    collection do
      post :return_headers_per_page
      post :delete_return_headers
    end
  end

  match "all_customers" => "customers#index", as: :all_customers

  resources :factories
  
  match "/factories/factory_detail/:party_id" => "factories#factory_detail", as: :factory_detail
  match "all_factories" => "factories#all_factories", as: :all_factories

  match "facility/inventory" => "pages#facility_inventory", as: :facility_inventory

  resources :orders do
    collection do
      get :find_return
    end
  end

  resources :promotion_rules do
    collection do
      match 'manage/:id' =>  "promotion_rules#manage"
      post '/update_promotion_rule'
      post '/update_rule_condition'
      post 'delete_rule_condition'
      post 'add_rule_condition_category'
      post 'update_rule_condition_category'
      post 'add_rule_condition_product'
      post 'update_rule_condition_product'
      post :delete_rule_action_category
      post :add_rule_action_category
      post :delete_rule_action
      post :update_rule_action
      post :delete_rule_action_product
      post :add_rule_action_product
      post :insert_rule_action
      post :delete_rule_condition_category
      post :delete_rule_condition_product
      post :add_rule_condition
      post :add_promotion_rule
      post :add_promotion_category
      post :delete_promotion_category
      post :add_promotion_product
      post :delete_promotion_product
    end
  end

  resources :promotion_rule_conditions

end

app/models/return_header.rb
class ReturnHeader < ActiveRecord::Base
  attr_accessible :billing_account_id, :currency_uom_id, :destination_facility_id, :entry_date, :fin_account_id, :from_party_id, :needs_inventory_receive, :origin_contact_mech_id, :payment_method_id, :return_id, :status_id, :supplier_rma_id, :to_party_id, :return_header_type_id
  # Composite primary keys
  # self.primary_keys = :return_id, :status_id
  # Association
  has_one :shipment
  belongs_to :status ,:class_name => 'ReturnHeaderStatus', :foreign_key => :status_id
  belongs_to :from_party ,:class_name => 'Party', :foreign_key => :from_party_id
  belongs_to :to_party ,:class_name => 'Party', :foreign_key => :to_party_id
  belongs_to :destination_facility ,:class_name => 'Facility', :foreign_key => :destination_facility_id
  belongs_to :origin_contact_mech, :class_name => 'ContactMech', :foreign_key => :origin_contact_mech_id
  belongs_to :payment_method, :class_name => 'PaymentMethod', :foreign_key => :payment_method_id
  belongs_to :return_header_type, :class_name => 'ReturnHeaderType', :foreign_key => :return_header_type_id
  belongs_to :billing_account, :class_name => 'BillingAccount', :foreign_key => :billing_account_id
  has_many :header_return_contact_meches , :class_name => 'ReturnContactMech', :foreign_key => :return_id
  has_many :return_items, :class_name => 'ReturnItem', :foreign_key => :return_id
  has_many :shipment_item_sources, :foreign_key => :return_id
  has_many :seq_shipment_item_sources, :class_name => 'ShipmentItemSource', :foreign_key => :return_item_seq_id

  def self.simple_search(params)
    if (params['content'].blank?)
      return_headers = ReturnHeader.where({})
    else
      type = params[:type]
      content = params[:content]
      if (type == 'promotion_name')
        return_headers = ReturnHeader.where([type + ' like ?', '%' + content + '%'])
      else
        return_headers = ReturnHeader.where({type => content})
      end
    end
    return return_headers
  end
end

app/models/return_header_type.rb
class ReturnHeaderType < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/return_headers_controller.rb
class ReturnHeadersController < ApplicationController
  before_filter :authenticate_user!
  layout "product_promotions"

  # GET /return_headers
  # GET /return_headers.json
  def index
    session[:promo_page] = 10 if session[:promo_page].blank?
    @return_headers = ReturnHeader.paginate(:page => 1, :per_page => session[:promo_page])
    @total = ReturnHeader.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @return_headers }
    end
  end

  # GET /return_headers/1
  # GET /return_headers/1.json
  def show
    @return_header = ReturnHeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @return_header }
    end
  end

  # GET /return_headers/new
  # GET /return_headers/new.json
  def new
    @return_header = ReturnHeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @return_header }
    end
  end

  # GET /return_headers/1/edit
  def edit
    @return_header = ReturnHeader.find(params[:id])
  end

  # POST /return_headers
  # POST /return_headers.json
  def create
    @return_header = ReturnHeader.new(params[:return_header])

    respond_to do |format|
      if @return_header.save
        format.html { redirect_to edit_return_header_path(@return_header), notice: 'Return header was successfully created.' }
        format.json { render json: @return_header, status: :created, location: @return_header }
      else
        format.html { render action: "new" }
        format.json { render json: @return_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /return_headers/1
  # PUT /return_headers/1.json
  def update
    @return_header = ReturnHeader.find(params[:id])

    respond_to do |format|
      if @return_header.update_attributes(params[:return_header])
        format.html { redirect_to edit_return_header_path(@return_header), notice: 'Return header was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @return_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /return_headers/1
  # DELETE /return_headers/1.json
  def destroy
    @return_header = ReturnHeader.find(params[:id])
    @return_header.destroy

    respond_to do |format|
      format.html { redirect_to return_headers_url }
      format.json { head :no_content }
    end
  end

  def return_headers_per_page
    session[:promo_page] = params['per'] if !params['per'].blank?
    params[:page] = 1 if params[:page].blank?

    @return_headers = ReturnHeader.simple_search(params)
    @return_header_temp = @return_headers.paginate(:page => params['page'], :per_page => session[:promo_page])
    @return_header = []
    @return_header_temp.each do |header|
      header_json = ActiveSupport::JSON.decode(header.to_json)
      header_json['return_header_type_id'] = header.return_header_type.description
      header_json['status_id'] = header.status.description
      header_json['payment_method_id'] = header.payment_method.description
      header_json['billing_account_id'] = header.billing_account.billing_account_id.to_s
      header_json['destination_facility_id'] = header.destination_facility.facility_name
      @return_header.push(header_json)
    end

    render json: {"data" => @return_header, "page" => (@return_headers.count / session[:promo_page].to_f).ceil, "per" => session[:promo_page]}
  end

  def delete_return_headers
    session[:promo_page] = params['per'] if !params['per'].blank?
    params[:page] = 1 if params[:page].blank?

    ReturnHeader.destroy_all(["id IN (?)", params['list']])
    length = params['list'].length
    @return_headers = ReturnHeader.simple_search(params)
    @return_header_temp = @return_headers.paginate(:page => params['page'], :per_page => session[:promo_page])
    @return_header = []
    @return_header_temp.each do |header|
      header_json = ActiveSupport::JSON.decode(header.to_json)
      header_json['return_header_type_id'] = header.return_header_type.description
      header_json['status_id'] = header.status.description
      header_json['payment_method_id'] = header.payment_method.description
      header_json['billing_account_id'] = header.billing_account.billing_account_id.to_s
      header_json['destination_facility_id'] = header.destination_facility.facility_name
      @return_header.push(header_json)
    end
    render json: {data: @return_header[(session[:promo_page].to_i - length)..(session[:promo_page].to_i)], page: (@return_headers.count / session[:promo_page].to_f).ceil}
  end
end

app/helpers/return_headers_helper.rb
module ReturnHeadersHelper
end

app/views/return_headers/_form.html.haml
= stylesheet_link_tag 'plugins/jquery-ui-timepicker-addon'
:javascript
  $(document).ready(function(){
    $('.datepicker').datetimepicker({
        showSecond: true,
        showMillisec: true,
        showButtonPanel: false,
        dateFormat: 'yy-mm-dd',
        timeFormat: 'HH:mm:ss.l',
        millisecText: 'Millisec',
      });
  });
-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
%div#return_header_form
  = form_for @return_header,:html => {:class => "stdform promotion_form"} do |f|
    - if @return_header.errors.any?
      #error_explanation
        %h2= "#{pluralize(@return_header.errors.count, "error")} prohibited this return_header from being saved:"
        %ul
          - @return_header.errors.full_messages.each do |msg|
            %li= msg
    %div#content-messages.content-messages.errorMessage.notification
      %a.close
    %p
      = f.label :return_header_type_id ,t('active_record.return_header.return_header_type_id')
      %span.field
        %select{:id => "return_header_type_id", :name => "return_header[return_header_type_id]"}
          - ReturnHeaderType.all.each do |type|
            - if type.id.to_s == @return_header.return_header_type_id.to_s
              %option{:value => type.id, :selected => "selected"}
                = type.description
            - else
              %option{:value => type.id}
                = type.description
    %p
      = f.label :status_id ,t('active_record.return_header.status_id')
      %span.field
        %select{:id => "status_id", :name => "return_header[status_id]"}
          - ReturnHeaderStatus.all.each do |status|
            - if status.id == @return_header.status_id
              %option{:value => status.id, :selected => "selected"}
                = status.description
            - else
              %option{:value => status.id}
                = status.description
    %p
      = f.label :from_party_id ,t('active_record.return_header.from_party_id')
      %span.field
        = f.text_field :from_party_id
    %p
      = f.label :to_party_id ,t('active_record.return_header.to_party_id')
      %span.field
        = f.text_field :to_party_id
    %p
      = f.label :payment_method_id ,t('active_record.return_header.payment_method_id')
      %span.field
        %select{:id => "payment_method_id", :name => "return_header[payment_method_id]"}
          - PaymentMethod.all.each do |payment|
            - if payment.id == @return_header.payment_method_id
              %option{:value => payment.id, :selected => "selected"}
                = payment.description
            - else
              %option{:value => payment.id}
                = payment.description
    %p
      = f.label :fin_account_id ,t('active_record.return_header.fin_account_id')
      %span.field
        = f.text_field :fin_account_id
    %p
      = f.label :billing_account_id ,t('active_record.return_header.billing_account_id')
      %span.field
        %select{:id => "billing_account_id", :name => "return_header[billing_account_id]"}
          - BillingAccount.all.each do |billing|
            - if billing.id == @return_header.billing_account_id
              %option{:value => billing.id, :selected => "selected"}
                = billing.billing_account_id
            - else
              %option{:value => billing.id}
                = billing.billing_account_id
    %p
      = f.label :entry_date ,t('active_record.return_header.entry_date')
      %span.field
        - if @return_header.entry_date.blank?
          = f.text_field :entry_date, {:value => Time.now.strftime("%Y-%m-%d %H:%M:%S:%L"), :class => "datepicker"}
        - else
          = f.text_field :entry_date, :class => "datepicker"
    %p
      = f.label :origin_contact_mech_id ,t('active_record.return_header.origin_contact_mech_id')
      %span.field
        = f.text_field :origin_contact_mech_id
    %p
      = f.label :destination_facility_id ,t('active_record.return_header.destination_facility_id')
      %span.field
        %select{:id => "destination_facility_id", :name => "return_header[destination_facility_id]"}
          - Facility.all.each do |facility|
            - if facility.id == @return_header.destination_facility_id
              %option{:value => facility.id, :selected => "selected"}
                = facility.facility_name
            - else
              %option{:value => facility.id}
                = facility.facility_name
    %p
      = f.label :needs_inventory_receive ,t('active_record.return_header.needs_inventory_receive')
      %span.field
        = f.check_box :needs_inventory_receive
    %p
      = f.label :currency_uom ,t('active_record.return_header.currency_uom_id')
      %span.field
        = @return_header.currency_uom_id
    %p
      = f.label :supplier_rma_id ,t('active_record.return_header.supplier_rma_id')
      %span.field
        = f.text_field :supplier_rma_id
    %p.stdformbutton
      = f.submit 'Save', :class => 'stdbtn btn_black'

app/views/return_headers/edit.html.haml
%h2 Editing Return Header

= render 'form'

app/views/return_headers/index.html.haml
-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
%div{"class" => "dataTables_wrapper", "id" => "lists-rtnhdr"}
  %div.contenttitle
    %h2.general
      %span
        = "All Return Headers"
  %div{"id" => "dyntable_length", "class" => "dataTables_length"}
    %a{"href" => "/return_headers/new"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.new')
    %a{"href" => "#", "id" => "btn-delete"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.delete')
  %div{"class" => "dataTables_filter", "id" => "dyntable_filter"}
    %div{"class" => "search-select"}
      %div
        = "Return Header ID"
      %span{"class" => "triangle"}
      %select{"class" => "search-content"}
        %option{"selected" => "selected", "value" => "id"}
          = "Return Header ID"
    %div{"class" => "btn-search"}
    %input{"type" => "text", "id" => "promo-search", "placeholder" => I18n.t('common.type_something')}
  %div.table-wrapper-content
    %table{"class" => "stdtable stdtablecb", "id" => "list-returnheaders"}
      %thead
        %th.head0.width64
          %input{"type" => "checkbox", "class" => "checkall"}
        %th.head1
          = "ID"
        %th.head0
          = t('active_record.return_header.return_header_type_id')
        %th.head0
          = t('active_record.return_header.status_id')
        %th.head0
          = t('active_record.return_header.from_party_id')
        %th.head0
          = t('active_record.return_header.to_party_id')
        %th.head0
          = t('active_record.return_header.payment_method_id')
        %th.head0
          = t('active_record.return_header.fin_account_id')
        %th.head0
          = t('active_record.return_header.billing_account_id')
        %th.head0
          = t('active_record.return_header.entry_date')
        %th.head0
          = t('active_record.return_header.origin_contact_mech_id')
        %th.head0
          = t('active_record.return_header.destination_facility_id')
        %th.head0
          = t('active_record.return_header.needs_inventory_receive')
        %th.head0
          = t('active_record.return_header.currency_uom_id')
        %th.head0
          = t('active_record.return_header.supplier_rma_id')
      %tbody
        - @return_headers.each do |return_header|
          %tr{"id" => "rthdr-"+return_header.id.to_s, "ref" => edit_return_header_path(return_header)}
            %td.center
              %span
                %input{"type" => "checkbox"}
            %td.center
              %span
                = return_header.id
            %td
              %span
                = return_header.return_header_type.description
            %td
              %span
                = return_header.status.description
            %td.center
              %span
                = return_header.from_party_id
            %td.center
              %span
                = return_header.to_party_id
            %td.center
              %span
                = return_header.payment_method.description
            %td.center
              %span
                = return_header.fin_account_id
            %td.center
              %span
                = return_header.billing_account.billing_account_id
            %td.wrap-content.center
              %span
                = return_header.entry_date
            %td.center
              %span
                = return_header.origin_contact_mech_id
            %td.center
              %span
                = return_header.destination_facility.facility_name
            %td.center
              %span
                = return_header.needs_inventory_receive
            %td.center
              %span
                = return_header.currency_uom_id
            %td.center
              %span
                = return_header.supplier_rma_id
  %div{"class" => "dataTables_paginate paging_full_numbers"}
    %label{"style" => "float: left"}
      Show
      %select{"size" => 1, "name" => "dyntable_length", "id" => "promotions-per-page"}
        - @nums = [10, 25, 50, 100]
        - @nums.each do |num|
          - if session[:promo_page].to_i == num
            %option{"value" => num, "selected" => "selected"}
              = num
          - if session[:promo_page].to_i != num
            %option{"value" => num}
              = num
    %div{"id" => "dyntable_paginate"}
      - @pages = (@total.to_f / session[:promo_page].to_f).ceil
      - if @pages > 1
        %span{"class" => "first paginate_button", "id" => "dyntable_first"}
          = I18n.t('common.first')
        %span{"class" => "previous paginate_button", "id" => "dyntable_previous"}
          = I18n.t('common.previous')
        %span{"class" => "paginate-body"}
          %span.paginate-body-inner
            - @pages.times do |page|
              - page = page + 1
              - if page == 1
                %span.paginate_active
                  = page
              - if page != 1
                %span.paginate_button
                  = page
        %span{"class" => "next paginate_button", "id" => "dyntable_next"}
          = I18n.t('common.next')
        %span{"class" => "last paginate_button", "id" => "dyntable_last"}
          = I18n.t('common.last')

app/views/return_headers/new.html.haml
%h1 New return_header

= render 'form'

- link_to 'Back', return_headers_path

app/views/return_headers/show.html.haml
-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice


= link_to 'Edit', edit_return_header_path(@return_header)
\|
= link_to 'Back', return_headers_path