config/routes.rb
Databox::Application.routes.draw do

  match "admin_customers" => "customers#admin_customers"
  post "admin_customers_next_page" => "customers#next_page"
  post "admin_customers_previous_page" => "customers#previous_page"
  get "search_customer" => "customers#search_customer"
  get "admin_customers_detail" => "customers#admin_customers_detail"
  
   get "products/overview/:id" => "products#overview"
   
   get "facility/control/main" => "facilities#main"
   post "facility/control/EditFacility" => "facilities#edit"
   post "facility/control/UpdateFacility" => "facilities#update"
   get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
   

 get "facility/control/main" => "facilities#main"
 post "facility/control/EditFacility" => "facilities#edit"
 post "facility/control/UpdateFacility" => "facilities#update"
 get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
 
 match "facility/:facility_id/inventory" => "pages#facility_inventory", as: :facility_inventory
 match "facility/edit_facility" => "pages#edit_facility", as: :edit_facility
 match "facility/selection" => "pages#facility_selection", as: :facility_selection
 match "facility/verify_pick" => "pages#verify_pick", as: :verify_pick
 match "facility/returns/receive" => "pages#receive_return", as: :receive_return
 match "facility/inventory/receive" => "pages#receive_inventory", as: :receive_inventory
 match "facility/pick_move_stock" => "pages#pick_move_stock", as: :pick_move_stock
 match "facility/picklist_options" => "pages#picklist_options", as: :picklist_options
 match "facility/picklist_manage" => "pages#picklist_manage", as: :picklist_manage
 match "facility/pack_order" => "pages#pack_order", as: :pack_order
 match "facility/inventory/transfers" => "pages#facility_transfers", as: :facility_transfers
 match "facility/facility_location" => "pages#facility_location", as: :facility_location
 match "facility/edit_inventory_item_details" => "pages#edit_inventory_item_details", as: :edit_inventory_item_details
 match "facility/edit_facility_location_details" => "pages#edit_facility_location_details", as: :edit_facility_location_details
 match "facility/edit_facility_inventory_items" => "pages#edit_facility_inventory_items", as: :edit_facility_inventory_items

  match "users/sign_up" => "pages#error"

  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations', :sessions => "users/sessions"},
  :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock'}
  devise_scope :user do
    match "party/" => "users/users#index"
    match "party/adduser" => "users/users#adduser"
    post "party/adduser"
    match "party/status" => "users/users#status"
    match "party/update_user" => "users/users#update_user"
    match "party/assign_role" => "users/users#assign_role"
    match "/users/check_email" => "users/users#check_email"
  end
  root :to => 'products#index'

  put "admins/update_user"
  put "admins/assign_role"

  get "pages/error"

  resources :products do
    collection do
      post :update_image
      post :update_product
      post :update_factory
      get :overview
      get :copy
      get :color
      match "weight_size/:sku" => "products#weight_size", as: :weight_size
      match "pricing/:sku" => "products#pricing", as: :pricing
      match "photos/:sku" => "products#photos", as: :photo
      get :moq_cost
      get :child
      get :find
      post  :results
    end
  end

  resources :product_promotions do
    collection do
      post :promotions_per_page
      post :delete_promotions
      get :stores
      post :stores_per_page
      post :delete_stores
      post :update_stores
      post :insert_stores

    end
  end

  resources :promotion_codes do
    collection do
      post :promotion_codes_per_page
      post :delete_promotion_codes
      get :mass_insert
      post :mass_insert
      post :add_email
      post :add_party
      post :delete_email
      post :delete_party
      post :check_party_id
    end
  end

  namespace :facility do
    resources :ship_rates do
      collection do
        post :get_for_country
        post :get_rates
        post :get_for_city_autocomplete
        post :shipment_per_page
        post :delete_shipment
        post :update_shipment
        post :get_quote
        post :get_for_country_autocomplete
        get :estimate
      end
    end
  end
  resources :return_headers do
    collection do
      post :return_headers_per_page
      post :delete_return_headers
    end
  end

  match "all_customers" => "customers#index", as: :all_customers

  resources :factories
  
  match "/factories/factory_detail/:party_id" => "factories#factory_detail", as: :factory_detail
  match "all_factories" => "factories#all_factories", as: :all_factories

  match "facility/inventory" => "pages#facility_inventory", as: :facility_inventory

  resources :orders do
    collection do
      get :find_return
    end
  end

  resources :promotion_rules do
    collection do
      match 'manage/:id' =>  "promotion_rules#manage"
      post '/update_promotion_rule'
      post '/update_rule_condition'
      post 'delete_rule_condition'
      post 'add_rule_condition_category'
      post 'update_rule_condition_category'
      post 'add_rule_condition_product'
      post 'update_rule_condition_product'
      post :delete_rule_action_category
      post :add_rule_action_category
      post :delete_rule_action
      post :update_rule_action
      post :delete_rule_action_product
      post :add_rule_action_product
      post :insert_rule_action
      post :delete_rule_condition_category
      post :delete_rule_condition_product
      post :add_rule_condition
      post :add_promotion_rule
      post :add_promotion_category
      post :delete_promotion_category
      post :add_promotion_product
      post :delete_promotion_product
    end
  end

  resources :promotion_rule_conditions

end

app/models/promotion_code.rb
class  PromotionCode < ActiveRecord::Base
  attr_accessible :created_by_user_login, :from_date, :last_modified_by_user_login, :product_promotion_code_id, :product_promotion_id, :require_email_or_party, :thru_date, :use_limit_per_code, :use_limit_per_customer, :user , :user_entered
  # Association
  belongs_to :product_promotion, :foreign_key => :product_promotion_id
  belongs_to :created_by_user_login, :class_name => 'User', :foreign_key =>  :created_by_user_login
  belongs_to :last_modified_by_user_login, :class_name => 'User', :foreign_key => :last_modified_by_user_login
  has_many :promotion_code_emails, :foreign_key =>  :product_promotion_code_id
  has_many :promotion_code_parties, :foreign_key => :product_promotion_code_id

  def self.simple_search(params)
    if (params['content'].blank?)
      promotion_codes = PromotionCode.where(:product_promotion_id => params[:product_promotion_id])
    else
      type = params[:type]
      content = params[:content]
      if (type == 'promotion_name')
        promotion_codes = PromotionCode.where([type + ' like ?' + ' AND product_promotion_id = ? ', '%' + content + '%', params[:product_promotion_id]])
      else
        promotion_codes = PromotionCode.where({type => content, :product_promotion_id => params[:product_promotion_id]})
      end
    end
    return promotion_codes
  end

  def self.check_id(previous=nil)
    str = ''
    str = previous.to_s
    if PromotionCode.where(:product_promotion_code_id => str).count != 0
      str = ''
    end

    return str
  end

  def self.random_string(type, length, previous=nil)
    str = ''
    if (type == "smart")
      begin
        str = ApplicationHelper.random_friendly_string('abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789', length)
      end while PromotionCode.where(:product_promotion_code_id => str).count != 0
    elsif (type == "sequence")
      if (previous == nil || previous == '')
        previous = ApplicationHelper.random_friendly_string('0123456789', length)
      end
      str = previous.to_i
      while PromotionCode.where(:product_promotion_code_id => str.to_s).count != 0
        str += 1
      end
    else
      begin
        str = ApplicationHelper.random_friendly_string('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length)
      end while PromotionCode.where(:product_promotion_code_id => str).count != 0
    end
    return str
  end


end

app/controllers/promotion_codes_controller.rb
class PromotionCodesController < ApplicationController
  # GET /promotion_codes
  # GET /promotion_codes.json
  before_filter :authenticate_user!
  layout "product_promotions"
  def index
    session[:promo_page] = 10 if session[:promo_page].nil?

    @promotion_codes = PromotionCode.where(:product_promotion_id => session[:product_promotion_id]).paginate(:page => 1, :per_page => session[:promo_page])
    @total = PromotionCode.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotion_codes }
    end
  end

  # GET /promotion_codes/1
  # GET /promotion_codes/1.json
  def show
    @promotion_code = PromotionCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion_code }
    end
  end

  # GET /promotion_codes/new
  # GET /promotion_codes/new.json
  def new
    @promotion_code = PromotionCode.new
    @product_promotion_id_collection = ProductPromotion.select("id, promotion_name")
    str = ''
    @product_promo_code_id=' '
    if params[:product_promotion_code_id].present?
      str = params[:product_promotion_code_id]
      @product_promo_code_id = PromotionCode.check_id(str)
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion_code }
    end
  end

  # GET /promotion_codes/1/edit
  def edit
    @promotion_code = PromotionCode.find(params[:id])
    @product_promo_code_id = @promotion_code.product_promotion_code_id
    @product_promotion_id_collection = ProductPromotion.select("id, promotion_name")
    @user_role_create = RolesUser.joins(:role).where("user_id=#{@promotion_code.created_by_user_login.id}").select("roles.name").first
    @user_role_modified = RolesUser.joins(:role).where("user_id=#{@promotion_code.last_modified_by_user_login.id}").select("roles.name").first
    @name_create = (@user_role_create.blank?) ? @promotion_code.created_by_user_login.email : @user_role_create.name
    @name_modified = (@user_role_modified.blank?) ? @promotion_code.last_modified_by_user_login.email : @user_role_modified.name
    @promotion_code_emails = @promotion_code.promotion_code_emails
    @promotion_code_parties = @promotion_code.promotion_code_parties
    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @promotion_code }
    end
  end

  # POST /promotion_codes
  # POST /promotion_codes.json
  def create
    uuid = UUID.new
    params[:promotion_code][:product_promotion_code_id] = params[:product_promotion_code_id].present? ? params[:product_promotion_code_id] : uuid.generate
    params[:promotion_code][:product_promotion_id] = session[:product_promotion_id]
    @promotion_code = PromotionCode.new(params[:promotion_code])
    @promotion_code.created_by_user_login = current_user
    @promotion_code.last_modified_by_user_login = current_user
    respond_to do |format|
      if @promotion_code.save
        format.html { redirect_to edit_promotion_code_path(@promotion_code.id), notice: 'Promotion code was successfully created.' }
        format.json { render json: @promotion_code, status: :created, location: @promotion_code }
      else
        format.html { render action: "new" }
        format.json { render json: @promotion_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotion_codes/1
  # PUT /promotion_codes/1.json
  def update
    @promotion_code = PromotionCode.find(params[:id])

    respond_to do |format|
      if @promotion_code.update_attributes(params[:promotion_code])
        @promotion_code.last_modified_by_user_login = current_user
        @promotion_code.save
        format.html { redirect_to '/promotion_codes', notice: 'Promotion code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promotion_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotion_codes/1
  # DELETE /promotion_codes/1.json
  def destroy
    @promotion_code = PromotionCode.find(params[:id])
    @promotion_code.destroy

    respond_to do |format|
      format.html { redirect_to promotion_codes_url }
      format.json { head :no_content }
    end
  end

  # ADD promotion code email  /promotion_codes/add_email
  def add_email
    @promotion_code_email = PromotionCodeEmail.new(params[:promotion_code_email])
    respond_to do |format|
      if @promotion_code_email.save
        format.json { render json: @promotion_code_email.to_json}
      else
        format.json { render json: @promotion_code_email.errors}
      end
    end
  end


  # ADD promotion code email  /promotion_codes/add_email
  def add_party
    @promotion_code_party = PromotionCodeParty.new(params[:promotion_code_party])
    respond_to do |format|
      if @promotion_code_party.save
        format.json { render json: @promotion_code_party}
      else
        format.json { render json: @promotion_code_party.errors}
      end
    end
  end

  def delete_email
    @promotion_code_email = PromotionCodeEmail.find(params[:id])
    @promotion_code_email.destroy

    respond_to do |format|

      format.json { head :no_content }
    end
  end

  def check_party_id
    p_id = ''
    p_id = params[:check_party_id].to_i
    if Party.where(:id => p_id).count != 0
      render :text => 'true'
    else
      render :text => 'false'
    end

  end

  def delete_party
    @promotion_code_party = PromotionCodeParty.find(params[:id])
    @promotion_code_party.destroy

    respond_to do |format|

      format.json { head :no_content }
    end
  end
  def mass_insert
    if request.post?
      str = nil
      if (params['user_entered'].nil?)
        params['user_entered'] = false
      else
        params['user_entered'] = true
      end
      if (params['require'].nil?)
        params['require'] = false
      else
        params['require'] = true
      end
      if (params['code_length'].present? && params['code_length'].to_i > 0)
        params['quantity'].to_i.times do
          str = PromotionCode.random_string(params['code_layout'], params['code_length'].to_i, str)
          PromotionCode.create({"product_promotion_code_id" => str, "user_entered" => params['user_entered'], "require_email_or_party" => params['require'],
                                "use_limit_per_code" => params['limit_per_code'], "use_limit_per_customer" => params['limit_per_customer'], "product_promotion_id" => session[:product_promotion_id], "created_by_user_login" => current_user, "last_modified_by_user_login" => current_user})
          flash[:success] = "success created!"
        end
      else
        flash[:error] = "error in created!"
      end
    end
  end

  def promotion_codes_per_page
    session[:promo_page] = params['per'] if !params['per'].nil?
    params[:page] = 1 if params[:page].nil?
    params[:product_promotion_id] = session[:product_promotion_id]
    @promotion_codes = PromotionCode.simple_search(params)
    @promotion_code = @promotion_codes.paginate(:page => params['page'], :per_page => session[:promo_page])
    render json: {"data" => @promotion_code, "page" => (@promotion_codes.count / session[:promo_page].to_f).ceil, "per" => session[:promo_page]}
  end

  def delete_promotion_codes
    session[:promo_page] = params['per'] if !params['per'].nil?
    params[:page] = 1 if params[:page].nil?
    length = params['list'].present? ? params['list'].length : 0
    PromotionCode.destroy_all(["id IN (?)", params['list']])
    params[:product_promotion_id] = session[:product_promotion_id]
    @promotion_codes = PromotionCode.simple_search(params)
    @promotion_code = @promotion_codes.paginate(:page => (params['page'].present? ? params['page'].to_i : 1), :per_page => session[:promo_page])

    render json: {data: @promotion_code[(session[:promo_page].to_i - length)..(session[:promo_page].to_i)], page: (@promotion_codes.count / session[:promo_page].to_f).ceil}
  end

  def check_promotion_code_party_id

  end

end

app/helpers/promotion_codes_helper.rb
module PromotionCodesHelper
end

app/views/promotion_codes/_form.html.haml
= stylesheet_link_tag 'plugins/jquery-ui-timepicker-addon'
= stylesheet_link_tag 'plugins/chosen'

:javascript
  $(document).ready(function(){
    $('.datepicker').datetimepicker({
        showSecond: true,
        showMillisec: true,
        showButtonPanel: false,
        dateFormat: 'yy-mm-dd',
        timeFormat: 'HH:mm:ss.l',
        millisecText: 'Millisec',
      });
    $(".promo-id-select").chosen();
  });

-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
= form_for @promotion_code,:html => {:class => "stdform promotion_form"} do |f|
  - if @promotion_code.errors.any?
    #error_explanation
      %h2= "#{pluralize(@promotion_code.errors.count, "error")} prohibited this promotion_code from being saved:"
      %ul
        - @promotion_code.errors.full_messages.each do |msg|
          %li= msg
  %div#content-messages.content-messages.errorMessage.notification
    %a.close
  %input{:name => 'product_promotion_code_id', :type => 'hidden', :value => @product_promo_code_id || @promotion_code.product_promotion_code_id}

  -unless @product_promo_code_id == ' '
    %p.promotion_code_id
      = f.label :product_promotion_code_id ,t('promotion_code.product_promotion_code_id')
      = f.label @product_promo_code_id || @promotion_code.product_promotion_code_id

  -if params[:action] == 'new'
    %p.product_promotion_id
      = f.label :promotion_id ,t('product_code.product_promotion_id')
      = f.label session[:product_promotion_id]
  -else
    %p.product_promotion_id
      = f.label :promotion_id ,t('product_code.product_promotion_id')
      %select{"class" => "promo-id-select","name" => 'promotion_code[product_promotion_id]'}
        - @product_promotion_id_collection.each do |promo_id_collection|
          %option{"value" => promo_id_collection.id}
            = ' [' + promo_id_collection.id.to_s + ']' + promo_id_collection.promotion_name

  %p
    = f.label :use_limit_per_code ,t('promotion_code.use_limit_per_code')
    %span.field
      = f.number_field :use_limit_per_code
  %p
    = f.label :use_limit_per_customer ,t('promotion_code.use_limit_per_customer')
    %span.field
      = f.number_field :use_limit_per_customer
  %p.select_promotion_code
    = f.label :from_date ,I18n.t('promotion_code.from_date')
    %span.field
      %input{"style" => "width: 300px", "type" => "text","name"=> "promotion_code[from_date]", "class" => "shortinput datepicker from_date", "value" => DateTime.now.strftime("%Y-%m-%d %H:%M:%S:%L")}

  %p.select_promotion_code
    = f.label :thru_date ,I18n.t('promotion_code.thru_date')
    %span.field
      %input{"style" => "width: 300px","name"=> "promotion_code[thru_date]", "type" => "text", "class" => "shortinput datepicker thru_date", "value" => DateTime.now.strftime("%Y-%m-%d %H:%M:%S:%L")}
  %p
    = f.label :user_entered ,I18n.t('promotion_code.user_entered')
    %span.field.checkbox
      = f.check_box :user_entered
  %p
    = f.label :require_email_or_party ,I18n.t('promotion_code.require_email_or_party')
    %span.field.checkbox
      = f.check_box :require_email_or_party
  %p.stdformbutton
    = f.submit I18n.t('common.save') ,:class => 'stdbtn btn_black'
  - unless params[:action] == "new"
    %p
      = f.label :created_by_user_login ,I18n.t('promotion_code.created_by_user_login')
      %span.field
        = '[' + @name_create + '] ON ' + @promotion_code.created_at.to_s(:db)
    %p
      = f.label :last_modified_by_user_login ,I18n.t('promotion_code.last_modified_by_user_login')
      %span.field
        = '[' + @name_modified + '] ON ' + @promotion_code.updated_at.to_s(:db)

app/views/promotion_codes/_form_new_promotion_rule.html.haml
%label.bold
  = t('promotion_rule.add_new_promotion_rule')
-#%div#list_promotion_rule
-#  - @promotion_rules.each do |rule|
-#    %div
-#      %a.btn.btn4.btn_trash{'data-id' => rule.id,:id => "delete_rule"}
-#      %span
-#        = rule.name
-#      %img#loading_delete_rule_name.hide{:src => "/assets/starlight/loaders/loader5.gif"}
%form.stdform.promotion_form
  %div#content-messages.content-messages.errorMessage.notification
    %a.close
  %p
    %span.field

      %input{:type => "text", :name => "promotion_rule_name[name]", :placeholder => t("promotion_rule.add_promotion_rule_name"),:id => "promotion_rule_name"}
      %button#add_promotion_rule_name
        = t('common.add')
      %img#loading_add_rule_name.hide{:src => "/assets/img/loader5.gif"}

app/views/promotion_codes/_form_promotion_code_email.html.haml
%label.bold
  = t('promotion_code_email.promotion_code_email')
%div#list_promotion_code_email
  - @promotion_code_emails.each do |email|
    %div
      %a.btn.btn4.btn_trash{'data-id' => email.id,:id => "delete_email"}
      %span
        = email.email
      %img#loading_delete_email.hide{:src => "/assets/img/loader5.gif"}
%form#form-add-email.stdform.promotion_form
  %div#content-messages.add-email.content-messages.errorMessage.notification
    %a.close
  %p
    %span.field
      %input{:type => "hidden",:name => "promotion_code_email[product_promotion_code_id]",:value => @promotion_code.id, :id => "promotion_code_email_product_promotion_code_id" }
      %input{:type => "email", :name => "promotion_code_email[email]", :placeholder => t("promotion_code_email.add_email"),:id => "promotion_code_email_email"}
      %button#add_promotion_code_email
        = t('common.add')
      %img#loading_add_email.hide{:src => "/assets/img/loader5.gif"}

app/views/promotion_codes/_form_promotion_code_party.html.haml
%label.bold
  = t('promotion_code_party.promotion_code_party')
%div#list_promotion_code_party
  - @promotion_code_parties.each do |party|
    %div
      %a.btn.btn4.btn_trash#delete_party{'data-id' => party.id}
      %span
        = party.party_id
      %img#loading_delete_party.hide{:src => "/assets/img/loader5.gif"}




%form#form-add-party-id.stdform.promotion_form
  %div#error-messages_label.hide
    .errorPartyId
      =t('promotion_code_party.error')
  %div#content-messages.party-id.content-messages.errorMessage.notification
    %a.close
  %p
    %span.field
      %input{:type => "hidden",:name => "promotion_code_party[product_promotion_code_id]",:value => @promotion_code.id, :id=> "promotion_code_party_product_promotion_code_id" }
      %input{:type => "text", :name => "promotion_code_party[party_id]",:placeholder => t("promotion_code_party.add_party_id"), :id => "promotion_code_party_party_id"}
      %button#add_promotion_code_party
        =t('common.add')
      %img#loading_add_party.hide{:src => "/assets/img/loader5.gif"}

app/views/promotion_codes/edit.html.haml
:javascript
  $(document).ready(function(){
    $('ul.maintabmenu').children('li').removeClass('current')
    $('ul.maintabmenu').children('li:nth-child(2)').addClass('current')
  });
%div.contenttitle
  %h2.form
    %span Editing promotion code

= render 'form'
- if @promotion_code.require_email_or_party?
  %div#require_email_or_party.show
    %hr
    = render 'form_promotion_code_email'
    %hr
    = render 'form_promotion_code_party'


- else
  %div#require_email_or_party.hide
    %hr
    = render 'form_promotion_code_email'
    %hr
    = render 'form_promotion_code_party'

app/views/promotion_codes/index.html.haml
:javascript
  $(document).ready(function(){
    $('ul.maintabmenu').children('li').removeClass('current')
    $('ul.maintabmenu').children('li:nth-child(2)').addClass('current')
  });

-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
%div{"class" => "dataTables_wrapper", "id" => "list-prdcode"}
  %div.contenttitle
    %h2.general
      %span
        = I18n.t('view.product.promotion.codes.title_list')
  %div{"id" => "dyntable_length", "class" => "dataTables_length"}
    %a{"href" => "/promotion_codes/new"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.new')
    %a{"href" => "/promotion_codes/mass_insert", "id" => "btn-mass-insert"}
      %button{"class" => "stdbtn"}
        = I18n.t('promotion_code.mass_insert')
    %a{"href" => "#", "id" => "btn-delete"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.delete')
  %div{"class" => "dataTables_filter", "id" => "dyntable_filter"}
    %div{"class" => "search-select"}
      %div
        = I18n.t('view.product.promotion.codes.code_id')
      %span{"class" => "triangle"}
      %select{"class" => "search-content"}
        %option{"selected" => "selected", "value" => "product_promotion_code_id"}
          = I18n.t('view.product.promotion.codes.code_id')
    %div{"class" => "btn-search"}
    %input{"type" => "text", "id" => "promo-search", "placeholder" => "type something...."}
  %div.table-wrapper-content
    %table{"class" => "stdtable stdtablecb", "id" => "list-procodes"}
      %thead
        %th.head0.width64
          %input{"type" => "checkbox", "class" => "checkall"}
        %th.head1
          = I18n.t('active_record.promotion_code.product_promotion_code_id')
        %th.head0
          = I18n.t('active_record.promotion_code.user_entered')
        %th.head1
          = I18n.t('active_record.promotion_code.require_email_or_party')
        %th.head0
          = I18n.t('active_record.promotion_code.use_limit_per_code')
        %th.head1
          = I18n.t('active_record.promotion_code.use_limit_per_customer')
        %th.head0
          = I18n.t('active_record.promotion_code.from_date')
        %th.head1
          = I18n.t('active_record.promotion_code.thru_date')
        %th.head0
          = I18n.t('common.created_at')
        %th.head1
          = I18n.t('active_record.promotion_code.created_by_user_login')
        %th.head0
          = I18n.t('common.last_modified')
        %th.head1
          = I18n.t('active_record.promotion_code.last_modified_by_user_login')
      %tbody
        - @promotion_codes.each do |promotion|
          %tr{"id" => "proid-"+promotion.id.to_s, "ref" => edit_promotion_code_path(promotion)}
            %td.center
              %span
                %input{"type" => "checkbox"}
            %td.wrap-content
              %span
                = promotion.product_promotion_code_id
            %td
              %span
                = promotion.user_entered
            %td
              %span
                = promotion.require_email_or_party
            %td
              %span
                = promotion.use_limit_per_code
            %td
              %span
                = promotion.use_limit_per_customer
            %td.wrap-content
              %span
                = promotion.from_date.presence || 'null'
            %td.wrap-content
              %span
                = promotion.thru_date.presence || 'null'
            %td.wrap-content
              %span
                = promotion.created_at.presence || 'null'
            %td
              %span
                = promotion.created_by_user_login.email
            %td.wrap-content
              %span
                = promotion.updated_at.presence || 'null'
            %td
              %span
                = promotion.last_modified_by_user_login.email
  %div{"class" => "dataTables_paginate paging_full_numbers"}
    %label{"style" => "float: left"}
      Show
      %select{"size" => 1, "name" => "dyntable_length", "id" => "promotions-per-page"}
        - @nums = [10, 25, 50, 100]
        - @nums.each do |num|
          - if session[:promo_page].to_i == num
            %option{"value" => num, "selected" => "selected"}
              = num
          - if session[:promo_page].to_i != num
            %option{"value" => num}
              = num
    %div{"id" => "dyntable_paginate"}
      - @pages = (@total.to_f / session[:promo_page].to_f).ceil
      - if @pages > 1
        %span{"class" => "first paginate_button", "id" => "dyntable_first"}
          = I18n.t('common.first')
        %span{"class" => "previous paginate_button", "id" => "dyntable_previous"}
          = I18n.t('common.previous')
        %span{"class" => "paginate-body"}
          %span.paginate-body-inner
            - @pages.times do |page|
              - page = page + 1
              - if page == 1
                %span.paginate_active
                  = page
              - if page != 1
                %span.paginate_button
                  = page
        %span{"class" => "next paginate_button", "id" => "dyntable_next"}
          = I18n.t('common.next')
        %span{"class" => "last paginate_button", "id" => "dyntable_last"}
          = I18n.t('common.last')

app/views/promotion_codes/new.html.haml
:javascript
  $(document).ready(function(){
    $('ul.maintabmenu').children('li').removeClass('current')
    $('ul.maintabmenu').children('li:nth-child(2)').addClass('current')
  });
%div.contenttitle
  %h2.form
    %span New promotion code
= render 'form'

app/views/promotion_codes/show.html.haml
%p#notice= notice

%p
  %b Product promotion code:
  = @promotion_code.product_promotion_code_id
%p
  %b Product promotion:
  = @promotion_code.promotion_id
%p
  %b User entered:
  = @promotion_code.user_entered
%p
  %b Require email or party:
  = @promotion_code.require_email_or_party
%p
  %b Use limit per code:
  = @promotion_code.use_limit_per_code
%p
  %b Use limit per customer:
  = @promotion_code.use_limit_per_customer
%p
  %b From date:
  = @promotion_code.from_date
%p
  %b Thru date:
  = @promotion_code.thru_date
%p
  %b Created by user login:
  = @promotion_code.created_by_user_login
%p
  %b Last modified by user login:
  = @promotion_code.last_modified_by_user_login

= link_to 'Edit', edit_promotion_code_path(@promotion_code)
\|
= link_to 'Back', promotion_codes_path