config/routes.rb
Databox::Application.routes.draw do

  match "admin_customers" => "customers#admin_customers"
  post "admin_customers_next_page" => "customers#next_page"
  post "admin_customers_previous_page" => "customers#previous_page"
  get "search_customer" => "customers#search_customer"
  get "admin_customers_detail" => "customers#admin_customers_detail"
  
   get "products/overview/:id" => "products#overview"
   
   get "facility/control/main" => "facilities#main"
   post "facility/control/EditFacility" => "facilities#edit"
   post "facility/control/UpdateFacility" => "facilities#update"
   get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
   

 get "facility/control/main" => "facilities#main"
 post "facility/control/EditFacility" => "facilities#edit"
 post "facility/control/UpdateFacility" => "facilities#update"
 get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
 
 match "facility/:facility_id/inventory" => "pages#facility_inventory", as: :facility_inventory
 match "facility/edit_facility" => "pages#edit_facility", as: :edit_facility
 match "facility/selection" => "pages#facility_selection", as: :facility_selection
 match "facility/verify_pick" => "pages#verify_pick", as: :verify_pick
 match "facility/returns/receive" => "pages#receive_return", as: :receive_return
 match "facility/inventory/receive" => "pages#receive_inventory", as: :receive_inventory
 match "facility/pick_move_stock" => "pages#pick_move_stock", as: :pick_move_stock
 match "facility/picklist_options" => "pages#picklist_options", as: :picklist_options
 match "facility/picklist_manage" => "pages#picklist_manage", as: :picklist_manage
 match "facility/pack_order" => "pages#pack_order", as: :pack_order
 match "facility/inventory/transfers" => "pages#facility_transfers", as: :facility_transfers
 match "facility/facility_location" => "pages#facility_location", as: :facility_location
 match "facility/edit_inventory_item_details" => "pages#edit_inventory_item_details", as: :edit_inventory_item_details
 match "facility/edit_facility_location_details" => "pages#edit_facility_location_details", as: :edit_facility_location_details
 match "facility/edit_facility_inventory_items" => "pages#edit_facility_inventory_items", as: :edit_facility_inventory_items

  match "users/sign_up" => "pages#error"

  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations', :sessions => "users/sessions"},
  :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock'}
  devise_scope :user do
    match "party/" => "users/users#index"
    match "party/adduser" => "users/users#adduser"
    post "party/adduser"
    match "party/status" => "users/users#status"
    match "party/update_user" => "users/users#update_user"
    match "party/assign_role" => "users/users#assign_role"
    match "/users/check_email" => "users/users#check_email"
  end
  root :to => 'products#index'

  put "admins/update_user"
  put "admins/assign_role"

  get "pages/error"

  resources :products do
    collection do
      post :update_image
      post :update_product
      post :update_factory
      get :overview
      get :copy
      get :color
      match "weight_size/:sku" => "products#weight_size", as: :weight_size
      match "pricing/:sku" => "products#pricing", as: :pricing
      match "photos/:sku" => "products#photos", as: :photo
      get :moq_cost
      get :child
      get :find
      post  :results
    end
  end

  resources :product_promotions do
    collection do
      post :promotions_per_page
      post :delete_promotions
      get :stores
      post :stores_per_page
      post :delete_stores
      post :update_stores
      post :insert_stores

    end
  end

  resources :promotion_codes do
    collection do
      post :promotion_codes_per_page
      post :delete_promotion_codes
      get :mass_insert
      post :mass_insert
      post :add_email
      post :add_party
      post :delete_email
      post :delete_party
      post :check_party_id
    end
  end

  namespace :facility do
    resources :ship_rates do
      collection do
        post :get_for_country
        post :get_rates
        post :get_for_city_autocomplete
        post :shipment_per_page
        post :delete_shipment
        post :update_shipment
        post :get_quote
        post :get_for_country_autocomplete
        get :estimate
      end
    end
  end
  resources :return_headers do
    collection do
      post :return_headers_per_page
      post :delete_return_headers
    end
  end

  match "all_customers" => "customers#index", as: :all_customers

  resources :factories
  
  match "/factories/factory_detail/:party_id" => "factories#factory_detail", as: :factory_detail
  match "all_factories" => "factories#all_factories", as: :all_factories

  match "facility/inventory" => "pages#facility_inventory", as: :facility_inventory

  resources :orders do
    collection do
      get :find_return
    end
  end

  resources :promotion_rules do
    collection do
      match 'manage/:id' =>  "promotion_rules#manage"
      post '/update_promotion_rule'
      post '/update_rule_condition'
      post 'delete_rule_condition'
      post 'add_rule_condition_category'
      post 'update_rule_condition_category'
      post 'add_rule_condition_product'
      post 'update_rule_condition_product'
      post :delete_rule_action_category
      post :add_rule_action_category
      post :delete_rule_action
      post :update_rule_action
      post :delete_rule_action_product
      post :add_rule_action_product
      post :insert_rule_action
      post :delete_rule_condition_category
      post :delete_rule_condition_product
      post :add_rule_condition
      post :add_promotion_rule
      post :add_promotion_category
      post :delete_promotion_category
      post :add_promotion_product
      post :delete_promotion_product
    end
  end

  resources :promotion_rule_conditions

end

app/models/product.rb
class Product < ActiveRecord::Base
  #has_paper_trail :on => [:update, :destroy]
  has_paper_trail
  attr_accessible :amount_uom_type_id, :bill_of_material_level, :charge_shipping, :comments, :default_shipment_box_type_id, :description, :fixed_amount, :in_shipping_box, :origin_geo_id, :product_name, :product_type_id, :require_amount, :require_inventory, :requirement_method_id, :returnable, :sales_disc_when_not_avail, :sales_discontinuation_date, :sales_introduction_date, :support_discontinuation_date, :supplier_id, :sku
  # Association
  has_one :product_gl_account
  has_one :shipment_receipt
  has_one :shipment_item
  has_one :shipment_package_content
  
  belongs_to :product_type
  belongs_to :requirement_methods
  belongs_to :default_shipment_box_type, :class_name => 'ShipmentBoxType', :foreign_key => :default_shipment_box_type_id
  
  has_many :communication_event_products
  has_many :return_items
  has_many :order_items
  has_many :asset_work_effort_asset_neededs, :class_name => 'WorkEffortAssetNeeded', :foreign_key => :asset_product_id
  has_many :work_effort_products
  has_many :party_needs
  has_many :sales_forecast_details
  has_many :supplier_products
  has_many :product_subscription_resources
  has_many :subscriptions
  has_many :product_assocs
  has_many :to_product_assocs, :class_name => 'ProductAssoc', :foreign_key => :to_product_id
  has_many :product_calculated_infos
  has_many :product_contents
  has_many :product_geos
  has_many :product_identifications
  has_many :product_parties
  has_many :product_prices
  has_many :product_reviews
  has_many :product_meters
  has_many :product_maintenances
  has_many :cost_components
  has_many :product_cost_component_calcs
  has_many :product_average_costs
  has_many :product_feature_appls
  has_many :product_config_item_appls
  has_many :product_config_option_products
  has_many :configurable_product_config_saveds, :class_name => 'ProductConfigSaved', :foreign_key => :configurable_product_id
  has_many :product_config_saved_options
  has_many :product_category_members
  has_many :instance_of_assets, :class_name => 'Asset', :foreign_key => :instance_of_product_id
  has_many :asset_products

  has_many :product_dimensions, :class_name => 'ProductDimension', :foreign_key => :product_id
  
  def name
    return product_name
  end
  
  def wholesale_price
    # need consideration
    product_prices.find(:first, :conditions => ["price_uom_id = ?", 'WHOLESALE_PRICE']).price
  end
  
  def retail_price
    product_prices.find(:first, :conditions => ["product_price_types.name = 'LIST_PRICE'"], :joins => [:price_type]).price
  end
  
  def weight
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_WEIGHT'"],  :joins => [:dimension_type]).value
  end
  
  def height
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_HEIGHT'"],  :joins => [:dimension_type]).value
  end
  
  def length
    #id = dim_id('PRODDIM_DEPTH')
    #product_dimensions.find(:first,:conditions => ["dimension_type_id = ?", id]).value
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_DEPTH'"],  :joins => [:dimension_type]).value
  end
  
  def width
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_WIDTH'"],  :joins => [:dimension_type]).value
  end
  
  def diameter
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_DIAMETER'"],  :joins => [:dimension_type]).value
  end
  
  def shoulder_drop
    product_dimensions.find(:first, :conditions => ["product_dimension_types.name = 'PRODDIM_SHOULDERDROP'"],  :joins => [:dimension_type]).value
  end
  
  def photo_url
    product_contents.find(:first, :conditions => ["product_content_types.name = 'ORIGINAL_IMAGE_URL'"], :joins => [:product_content_type]).content_location
  end
  

  has_many :promotion_products
  has_many :promotion_rule_condition_products
  has_many :promotion_rule_action_products
  
  has_attached_file :photo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :description, :name, :parent_id
  # Association
  belongs_to :parent, :class_name => 'ProductType', :foreign_key => :parent_id
  has_many :children, :class_name => 'ProductType', :foreign_key => :parent_id
  has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #to remove devise authentication, comment following before_filter function out.
  before_filter :authenticate_user!

  layout "products"
  
  def index
    if params[:query]
      @products = Product.where("product_name LIKE '%#{params[:query]}%' OR sku LIKE '%#{params[:query]}%'").page(params[:page]).per_page(30)
      @total  = @products.count
    else
      @products = Product.page(params[:page]).per_page(10)
      @total  = @products.count
    end
  end

  def show
    id = params[:id]
    @product = Product.find(id)
    @contents = @product.product_contents
    @history  = @product.versions
  end

  # Update Product information
  def update_product
    product =  params[:product]
    @product = Product.find(params[:product][:id])
    @product.update_attributes(product)
    redirect_to "/products/"+params[:product][:id]
  end

  def update_image
    if params[:product_content]
      #ProductContent.
      ProductContent.create(params[:product_content])
      redirect_to "/products/"+params[:product_content][:product_id]
    end
  end

  def update_factory
    #puts params
    @product = Product.find(params[:product][:id])
    @product.product_parties.first.party.organizations.first.update_attributes(params[:organization])
    @product.supplier_products.first.update_attributes(params[:supplier_product])
    redirect_to "/products/#{@product.id}"
  end

  def new
    #Just render form for creating a new product.
  end
  # Create a new product
  def create
  if params[:product_content]
    @product=Product.new()
    @product[:product_name] = "Sample Product Name w Img"
    @product[:product_type_id] = "1"
    @product[:sku] = "XIMGX"
    @product.save()

    content = params[:product_content]
    @product.product_contents.create(content)
  end


  if params[:product]
    @product= Product.new(params[:product])
    @product[:product_type_id] = "1"
    @product[:sku] = "XXXX"
    @product.save()
  else
    if params[:factory_info]
      @product=Product.new()
      @product[:product_name] = "Sample Product Name"
      @product[:product_type_id] = "1"
      @product[:sku] = "XXXX"
      @product.save()

      ##Other Relative Entites
      #asset_product = AssetProduct.new()
      #asset_product[:product_id]=@product.id
      ##Temporary assignment of Asset id
      #asset_product[:asset_id]="1"
      #asset_product[:quantity_on_hand_total]="00"
      #asset_product.save()
      #
      #cost_component =  @product.cost_components.new()
      #cost_component[:cost] = "0000"
      #cost_component.save()
      #
      ##@product.asset_products.first.asset.quantity_on_hand_total
      #
      #prod_price  = @product.product_prices.new()
      #prod_price[:price] = "0000"
      #prod_price.save()
      #
      #supp_prod = @product.supplier_products.new()
      #supp_prod[:standard_lead_time_days] = params[:factory_info][:standard_lead_time_days]
      #supp_prod.save()
      @factoryInfo  = params[:factory_info]
    end
    end
    #Other Relative Entites
    asset_product = AssetProduct.new()
    asset_product[:product_id]=@product.id
    #Temporary assignment of Asset id
    asset_product[:asset_id]="1"
    asset_product[:quantity_on_hand_total]="00"
    asset_product.save()

    cost_component =  @product.cost_components.new()
    cost_component[:cost] = "0000"
    cost_component.save()

    #@product.asset_products.first.asset.quantity_on_hand_total

    prod_price  = @product.product_prices.new()
    prod_price[:price] = "0000"
    prod_price.save()

    prod_party = ProductParty.new()
    prod_party[:party_id] = 1
    prod_party[:product_id] = @product.id
    prod_party.save()

    supp_prod = @product.supplier_products.new()
    if params[:factory_info]
      supp_prod[:standard_lead_time_days] = params[:factory_info][:standard_lead_time_days]
    else
      supp_prod[:standard_lead_time_days] = "0"
    end
    supp_prod.save()
  redirect_to "/products/#{@product.id}"

  end


  def find
    #Just render form for Product Search
  end

  # Search a product wit given search parameters
  def results
    #@products = Product.where("id = ? OR supplier_id = ? OR product_name = ? OR description = ?", params[:product][:product_id],params[:product][:supplier_id], params[:product][:product_name], params[:product][:description])

    @products = Product.where("id = ? AND product_name = ? AND description = ?", params[:product][:product_id], params[:product][:product_name], params[:product][:description])
  end
  
  def overview
    sku = params[:id]
    @product  = Product.find_by_id(sku)
    #@dimention = @product.product_dimentions.find(:conditions => "dimension_type_id = 1")
  end

  def photos
    @product = Product.where("sku = ? ", params[:sku]).first
  end
  
  def copy
  
  end
  
  def color
  
  end
  
  def pricing
    find_product_by_sku
    ap @product
  end
  
  def moq_cost
  
  end
  
  def weight_size
    find_product_by_sku
    ap @product
  end

  def find_product_by_sku
     @product = Product.where("sku = ? ", params[:sku]).first
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def pipeline?
    params[:controllers] == 'pipelines'
  end

  def products?
    params[:controllers] == 'products'
  end

  def orders?
    params[:controllers] == 'orders'
  end

  def customers?
    params[:controllers] == 'customers'
  end

  def suppliers?
    params[:controllers] == 'suppliers'
  end

  def dashboard?
    params[:controllers] == 'dashboard'
  end

  def wiki?
    params[:controllers] == 'wiki'
  end
  
  def overview?
    params[:controllers] == 'products' && params[:action] == 'overview'
  end
  
  def photos?
    params[:controllers] == 'products' && params[:action] == 'photos'
  end
  
  def copy?
    params[:controllers] == 'products' && params[:action] == 'copy'
  end
  
  def color?
    params[:controllers] == 'products' && params[:action] == 'color'
  end
  
  def volume?
    params[:controllers] == 'products' && params[:action] == 'weight_size'
  end
  
  def pricing?
    params[:controllers] == 'products' && params[:action] == 'pricing'
  end
  
  def cost?
    params[:controllers] == 'products' && params[:action] == 'moq_cost'
  end
  
  def child?
    params[:controllers] == 'products' && params[:action] == 'child'
  end
end

app/views/products/_header.html.haml
%header#account-header
  #pre-header
  #main-header
    .inner
      #brand.push-left
        %h2
          %a{:href => "index.html"} OrderWithMe.com
      #shop-nav
        %nav
          %ul
            %li
              %a{:href => "/"} Dashboard
            %li
              %a{:href => "/"} Projects
            %li
              %a{:href => products_path}
                Products
                %i.icon-caret
              %ul
                %li
                  = link_to "Product", products_path
                %li
                  %a{:href => "/product_promotions"} Promotions
                - if session[:product_promotion_id].present?
                  %li
                    %a{"href" => "/promotion_codes"} Codes
                  %li
                    %a{"href" => "/promotion_rules/manage/" + session[:product_promotion_id].to_s} Rules
                  %li
                    %a{"href" => "/product_promotions/stores"} Stores
            %li{:class => (action_name.eql?("index") and controller_name.eql?("factories")) ? "active" : ""}
              %a{:href => "/"}
                Factories
                %i.icon-caret
              %ul
                %li
                  = link_to "All Factories", factories_path
                %li
                  %a{:href => "admin-all-factory-orders.html"} Factory POs
            %li
              %a{:href => "/"}
                Customers
                %i.icon-caret
              %ul
                %li
                  = link_to "All Customers", all_customers_path
                %li
                  %a{:href => "admin-all-customer-orders.html"} Customer SOs
            %li
              %a{:href => "/"} Warehouse
      #account-nav
        %nav
          %ul
            %li
              %a{:href => "#"}
                - if user_signed_in?
                  = current_user.email
                %i.icon-caret
              %ul
                %li
                  #{link_to "Log Out", destroy_user_session_path, method: :delete}

app/views/products/_header_new.html.haml
%header.header.radius3
  #headerinner
    %a{:href => "/"}
      %img{"src" => "/assets/logo-small.png", "style" => "padding: 8px;"}
    .headright
      %div.headercolumn &nbsp;
      %div#searchPanel.headercolumn
        %div.searchbox
          %form{"method" => "post"}
            %input{"type" => "text", "id" => "keyword", "name" => "keyword", "class" => "radius2 ui-autocomplete-input", "value" => "Search here", "autocomplete" => "off", "role" => "textbox", "aria-autocomplete" => "list", "aria-haspopup" => "true"}
      %div#notiPanel.headercolumn
        %div.notiwrapper
          %a.notialert.radius2 5
      %div#userPanel.headercolumn
        %a.userinfo.radius2
          %img{"src" => "/assets/starlight/avatar.png", "class" => "radius2"}
          %span
            %strong
              - if user_signed_in?
                = current_user.email
        %div{"style" => "width: 151px;", "class" => "userdrop"}
          %ul
            %li
              %a{"href" => ""} Profile
            %li
              %a{"href" => ""} Account Setting
            %li
              = link_to "Log Out", destroy_user_session_path, method: :delete

app/views/products/_left_nav_bar.html.haml
#leftMenu
  .mainleft
    .mainleftinner
      #products.leftmenu
        %ul.idTabs.leftMenuStyle
          %li
            %a.search{:href => "/products"}
              %span
                %em Find Products
          %li
            %a.list{:href => "/products"}
              %span 
                %em Order Of Products

app/views/products/_topbar.html.haml
.topbar
  %ul
    %li{:class => "#{'current' if overview?}"}
      %a{:href => "#{overview_products_path}"} Overview
    %li{:class => "#{'current' if photos?}"}
      %a{:href => "#{photos_products_path}"} Photos
    %li{:class => "#{'current' if copy?}"}
      %a{:href => "#{copy_products_path}"} Copy
    %li{:class => "#{'current' if color?}"}
      %a{:href => "#{color_products_path}"} Color
    %li{:class => "#{'current' if volume?}"}
      %a{:href => "#{weight_size_products_path(10000)}"} Weight & Size
    %li{:class => "#{'current' if pricing?}"}
      %a{:href => "#{pricing_products_path(10000)}"} Pricing
    %li{:class => "#{'current' if cost?}"}
      %a{:href => "#{moq_cost_products_path}"} MOQ & Cost
    %li{:class => "#{'current' if child?}"}
      %a{:href => "#{child_products_path}"} Parent / Child

app/views/products/find.html.haml
// Main Left Division: For side bar Navigation.
= render "shared/left_nav_bar", :tab => "find-products"
.mainwrapperinner
  .maincontent.noright
    .maincontentinner
      %ul.maintabmenu
        %li.current
          %a{:href => "#"} Find Products
      .content
        %form#form1.stdform{:action => "/products/results", :method => "post"}
          %p
            %label Product ID
            %span.field
              %input#product-id.longinput{:name => "product[product_id]", :type => "text"}

          -#%p
          -#  %label Product Supplier ID
          -#  %span.field
          -#    %input#product-supp-id.longinput{:name => "product[supplier_id]", :type => "text"}


          %p
            %label Product Name
            %span.field
              %input#product-name.longinput{:name => "product[product_name]", :type => "text"}

          %p
            %label Product Description
            %span.field
              %input#product-desc.longinput{:name => "product[description]", :type => "text"}

          %br/
          %p.stdformbutton
            %button.submit.radius2 Find

-#CREATE TABLE "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "product_type_id" integer, "product_name" text, "description" text, "comments" text, "sales_introduction_date" datetime, "sales_discontinuation_date" datetime, "sales_disc_when_not_avail" boolean, "support_discontinuation_date" datetime, "require_inventory" boolean, "requirement_method_id" boolean, "charge_shipping" boolean, "in_shipping_box" boolean, "default_shipment_box_type_id" integer, "returnable" boolean, "require_amount" boolean, "amount_uom_type_id" integer, "fixed_amount" decimal, "origin_geo_id" integer, "bill_of_material_level" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)

app/views/products/moq_cost.html.haml
%table{:cellspacing => 0, :cellpadding => 0, :border => 0}
  %tbody
    %tr
      %td
        .rightColumn
          .previewContainer
            .theimage
              %a.showImages{:href => "/products"}
                %img{:width => 335, :height => 253, :src => "/assets/10000-01.jpg"}
            .amendContainer
              .uploadtitle.h4bold
                %span 
                  Product #10000 (T464 gold)
                %span
                  %a{:id => "popup", :class => "historyImage", :href => "javascript:void(0);"}
                #dialog{:style => "display: none;"}
                  %div
                    %span.h3bold Product History #10000
                  %div
                    %table{:cellspacing => 0, :cellpadding => 0, :border => 0, :class => "stdtable historytable"}
                      %tbody
                        %tr
                          %th.head0
                            %span.h1history name
                          %td
                            %p Cassie Gold
                          %td.date
                            %p.warpDate 01/24/2012 10:05:49
                          %td
                            %p Sam Hamilton (sam.hamilton)
                        %tr
                          %th.head1
                            %span.h1history description
                          %td.description
                            %p Gold chain with seven charms intertwined with brown beads.
                          %td.date
                            %p.warpDate 01/12/2012 05:12:43
                          %td
                            %p Mitch Fu (mitch.fu)
                        %tr
                          %th.head0
                            %span.h1history photo
                          %td
                            %p 10000-01.jpg
                            %p 10000-02.jpg
                          %td.date
                            %p.warpDate 01/24/2012 10:05:49
                            %p.warpDate 01/24/2012 10:05:49
                          %td
                            %p Sam Hamilton (sam.hamilton)
                            %p Sam Hamilton (sam.hamilton)
                        %tr
                          %th.head1
                            %span.h1history price
                          %td
                            %p Wholesale : $5.00
                            %p Retail : $17.99
                          %td.date
                            %p.warpDate 01/24/2012 10:05:49
                            %p.warpDate 01/24/2012 10:05:49
                          %td
                            %p Summer Schartz (summer.schartz)
                            %p Summer Schartz (summer.schartz)
                        %tr
                          %th.head0
                            %span.h1history weight
                          %td
                            %p 0.055 kg
                          %td.date
                            %p.warpDate 01/24/2012 10:05:49
                            %p.warpDate 01/24/2012 10:05:49
                          %td
                            %p Sam Hamilton (sam.hamilton)
                        %tr
                          %th.head1
                            %span.h1history size
                          %td
                            %p 76cm
                          %td.date
                            %p.warpDate 01/24/2012 10:05:49
                          %td
                            %p Sam Hamilton (sam.hamilton)
              .amendInfoWrap
                .row
                  .left
                    %span.h4bold Factory Price
                    %br/
                    18 RMB
                  .left
                    %span.h4bold Min Qty
                    %br/
                    240
                %form{:class => "h4bold", :name => "updateProductOverviewMOQAndCost", :action => "updateProductOverviewMOQAndCost", :method => "post"}
                  %input{:type => "hidden", :value => "10077", :name => "partyId"}
                  %input{:type => "hidden", :value => "10000", :name => "productId"}
                  %input{:type => "hidden", :value => "2012-01-03 03:03:45.380", :name => "availableFromDate"}
                  %input{:type => "hidden", :value => "30", :name => "standardLeadTimeDays"}
                  %input{:type => "hidden", :value => "T464 gold", :name => "supplierProductId"}
                  %input{:type => "hidden", :value => "moqcost", :name => "menuType"}
                  .row
                    %input{:class => "myTextField3 marginLeftTop", :type => "text", :value => "240", :name => "minimumOrderQuantity"} &nbsp;Minimum Order Quantity
                    %br/
                    %input{:class => "myTextField3 marginLeftTop", :type => "text", :value => "18", :name => "lastPrice"} &nbsp;Cost (RMB)
                  %button{:id => "productMOQAndCostSubmitButton", :class => "btnSubmit", :style => "float: right;"} Submit 
            

app/views/products/results.html.haml
// Main Left Division: For side bar Navigation.
= render "shared/left_nav_bar", :tab => "find-products"
.mainwrapperinner
  .maincontent.noright
    .maincontentinner
      %ul.maintabmenu
        %li.current
          %a{:href => "#"} Search Results
      .content
        - @products.each do |product|
          =product.product_name
          %br