config/routes.rb
Databox::Application.routes.draw do

  match "admin_customers" => "customers#admin_customers"
  post "admin_customers_next_page" => "customers#next_page"
  post "admin_customers_previous_page" => "customers#previous_page"
  get "search_customer" => "customers#search_customer"
  get "admin_customers_detail" => "customers#admin_customers_detail"
  
   get "products/overview/:id" => "products#overview"
   
   get "facility/control/main" => "facilities#main"
   post "facility/control/EditFacility" => "facilities#edit"
   post "facility/control/UpdateFacility" => "facilities#update"
   get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
   

 get "facility/control/main" => "facilities#main"
 post "facility/control/EditFacility" => "facilities#edit"
 post "facility/control/UpdateFacility" => "facilities#update"
 get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
 
 match "facility/:facility_id/inventory" => "pages#facility_inventory", as: :facility_inventory
 match "facility/edit_facility" => "pages#edit_facility", as: :edit_facility
 match "facility/selection" => "pages#facility_selection", as: :facility_selection
 match "facility/verify_pick" => "pages#verify_pick", as: :verify_pick
 match "facility/returns/receive" => "pages#receive_return", as: :receive_return
 match "facility/inventory/receive" => "pages#receive_inventory", as: :receive_inventory
 match "facility/pick_move_stock" => "pages#pick_move_stock", as: :pick_move_stock
 match "facility/picklist_options" => "pages#picklist_options", as: :picklist_options
 match "facility/picklist_manage" => "pages#picklist_manage", as: :picklist_manage
 match "facility/pack_order" => "pages#pack_order", as: :pack_order
 match "facility/inventory/transfers" => "pages#facility_transfers", as: :facility_transfers
 match "facility/facility_location" => "pages#facility_location", as: :facility_location
 match "facility/edit_inventory_item_details" => "pages#edit_inventory_item_details", as: :edit_inventory_item_details
 match "facility/edit_facility_location_details" => "pages#edit_facility_location_details", as: :edit_facility_location_details
 match "facility/edit_facility_inventory_items" => "pages#edit_facility_inventory_items", as: :edit_facility_inventory_items

  match "users/sign_up" => "pages#error"

  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations', :sessions => "users/sessions"},
  :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock'}
  devise_scope :user do
    match "party/" => "users/users#index"
    match "party/adduser" => "users/users#adduser"
    post "party/adduser"
    match "party/status" => "users/users#status"
    match "party/update_user" => "users/users#update_user"
    match "party/assign_role" => "users/users#assign_role"
    match "/users/check_email" => "users/users#check_email"
  end
  root :to => 'products#index'

  put "admins/update_user"
  put "admins/assign_role"

  get "pages/error"

  resources :products do
    collection do
      post :update_image
      post :update_product
      post :update_factory
      get :overview
      get :copy
      get :color
      match "weight_size/:sku" => "products#weight_size", as: :weight_size
      match "pricing/:sku" => "products#pricing", as: :pricing
      match "photos/:sku" => "products#photos", as: :photo
      get :moq_cost
      get :child
      get :find
      post  :results
    end
  end

  resources :product_promotions do
    collection do
      post :promotions_per_page
      post :delete_promotions
      get :stores
      post :stores_per_page
      post :delete_stores
      post :update_stores
      post :insert_stores

    end
  end

  resources :promotion_codes do
    collection do
      post :promotion_codes_per_page
      post :delete_promotion_codes
      get :mass_insert
      post :mass_insert
      post :add_email
      post :add_party
      post :delete_email
      post :delete_party
      post :check_party_id
    end
  end

  namespace :facility do
    resources :ship_rates do
      collection do
        post :get_for_country
        post :get_rates
        post :get_for_city_autocomplete
        post :shipment_per_page
        post :delete_shipment
        post :update_shipment
        post :get_quote
        post :get_for_country_autocomplete
        get :estimate
      end
    end
  end
  resources :return_headers do
    collection do
      post :return_headers_per_page
      post :delete_return_headers
    end
  end

  match "all_customers" => "customers#index", as: :all_customers

  resources :factories
  
  match "/factories/factory_detail/:party_id" => "factories#factory_detail", as: :factory_detail
  match "all_factories" => "factories#all_factories", as: :all_factories

  match "facility/inventory" => "pages#facility_inventory", as: :facility_inventory

  resources :orders do
    collection do
      get :find_return
    end
  end

  resources :promotion_rules do
    collection do
      match 'manage/:id' =>  "promotion_rules#manage"
      post '/update_promotion_rule'
      post '/update_rule_condition'
      post 'delete_rule_condition'
      post 'add_rule_condition_category'
      post 'update_rule_condition_category'
      post 'add_rule_condition_product'
      post 'update_rule_condition_product'
      post :delete_rule_action_category
      post :add_rule_action_category
      post :delete_rule_action
      post :update_rule_action
      post :delete_rule_action_product
      post :add_rule_action_product
      post :insert_rule_action
      post :delete_rule_condition_category
      post :delete_rule_condition_product
      post :add_rule_condition
      post :add_promotion_rule
      post :add_promotion_category
      post :delete_promotion_category
      post :add_promotion_product
      post :delete_promotion_product
    end
  end

  resources :promotion_rule_conditions

end

app/models/product_promotion.rb
class ProductPromotion < ActiveRecord::Base
  attr_accessible :billback_factor, :override_org_party_id, :promotion_name, :promotion_show_to_customer, :promotion_text, :require_code, :use_limit_per_customer, :use_limit_per_order, :use_limit_per_promotion, :user_entered, :user_id, :created_by_user_login, :last_modified_by_user_login
  # Association
  belongs_to :user
  belongs_to :created_by_user_login, :class_name => 'User', :foreign_key =>  :created_by_user_login
  belongs_to :last_modified_by_user_login, :class_name => 'User', :foreign_key => :last_modified_by_user_login
  has_many :promotion_codes, :foreign_key => :product_promotion_id
  has_many :promotion_products, :foreign_key => :product_promotion_id
  has_many :promotion_categories, :foreign_key => :product_promotion_id
  has_many :promotion_rules
  has_many :promotion_stores, :foreign_key => :product_promotion_id
  validates :promotion_name, :presence => {:message => I18n.t("product_promotion.validate.promotion_name")}


  def self.promotion_by_user(user_id)
      @promotions = self.where(:user_id => user_id).order("id ASC")
      @promotions.map{ |item| ["[#{item.id}]#{item.promotion_name}", item.id] }
  end

  def self.simple_search(params)
    if (params['content'].blank?)
      product_promotions = ProductPromotion.where({})
    else
      type = params[:type]
      content = params[:content]
      if (type == 'promotion_name')
        product_promotions = ProductPromotion.where([type + ' like ?', '%' + content + '%'])
      elsif (type == 'user_entered')
        content = content.downcase
        if (content == 't' || content == 'true' || content == 1)
          content = 't'
        elsif (content == 'f' || content == 'false' || content == 0)
          content = 'f'
        end
        product_promotions = ProductPromotion.where({type => content})
      else
        product_promotions = ProductPromotion.where({type => content})
      end
    end
    return product_promotions
  end

  def self.check_id(previous=nil)
    str = ''
    str = previous.to_s
    if ProductPromotion.where(:promotion_id => str).count != 0
      str = ''
    end

    return str
  end

  def self.random_string(type, length, previous=nil)
    str = ''
    if (type == "smart")
      begin
        str = ApplicationHelper.random_friendly_string('abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789', length)
      end while ProductPromotion.where(:promotion_id => str).count != 0
    elsif (type == "sequence")
      if (previous == nil || previous == '')
        previous = ApplicationHelper.random_friendly_string('0123456789', length)
      end
      str = previous.to_i
      while ProductPromotion.where(:promotion_id => str.to_s).count != 0
        str += 1
      end
    else
      begin
        str = ApplicationHelper.random_friendly_string('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length)
      end while ProductPromotion.where(:promotion_id => str).count != 0
    end
    return str
  end
end

app/controllers/product_promotions_controller.rb
class ProductPromotionsController < ApplicationController
  before_filter :authenticate_user!
  layout "product_promotions"

  # GET /product_promotions
  # GET /product_promotions.json
  def index
    session[:promo_page] = 10 if session[:promo_page].blank?
    session.delete(:product_promotion_id)
    @product_promotions = ProductPromotion.paginate(:page => 1, :per_page => session[:promo_page])
    @total = ProductPromotion.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_promotions }
    end
  end

  # GET /product_promotions/1
  # GET /product_promotions/1.json
  def show
    @product_promotion = ProductPromotion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_promotion }
    end
  end

  # GET /product_promotions/new
  # GET /product_promotions/new.json
  def new
    @product_promotion = ProductPromotion.new
    #str = ''
    #@promotion_id = ' '
    #if params[:promotion_id].present?
    #  str = params[:promotion_id]
    #  @promotion_id = ProductPromotion.check_id(str)
    #end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_promotion }
    end
  end

  # GET /product_promotions/1/edit
  def edit
    session[:product_promotion_id] = params[:id]
    @product_promotion = ProductPromotion.find(params[:id])

  end

  # POST /product_promotions
  # POST /product_promotions.json
  def create
    @product_promotion = ProductPromotion.create(params[:product_promotion])
    @product_promotion.created_by_user_login = current_user
    @product_promotion.last_modified_by_user_login = current_user
    @product_promotion.update_attribute(:user_id, current_user.id) if @product_promotion.user_id.blank?
    respond_to do |format|
      if @product_promotion.save
        format.html { redirect_to edit_product_promotion_path(@product_promotion.id), notice: 'Product promotion was successfully created.'  }
        format.json { render json: @product_promotion, status: :created, location: @product_promotion }
      else
        format.html { render action: "new" }
        format.json { render json: @product_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_promotions/1
  # PUT /product_promotions/1.json
  def update
    @product_promotion = ProductPromotion.find(params[:id])
    respond_to do |format|
      if @product_promotion.update_attributes(params[:product_promotion])
        format.html { redirect_to  '/product_promotions', notice: 'Product promotion was successfully updated.'}
        format.json { render json: @product_promotion }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_promotions/1
  # DELETE /product_promotions/1.json
  def destroy
    @product_promotion = ProductPromotion.find(params[:id])
    @product_promotion.destroy

    respond_to do |format|
      format.html { redirect_to product_promotions_url }
      format.json { head :no_content }
    end
  end

  def promotions_per_page
    session[:promo_page] = params['per'] if !params['per'].blank?
    params[:page] = 1 if params[:page].blank?

    @product_promotions = ProductPromotion.simple_search(params)
    @product_promotion = @product_promotions.paginate(:page => params['page'], :per_page => session[:promo_page])
    render json: {"data" => @product_promotion, "page" => (@product_promotions.count / session[:promo_page].to_f).ceil, "per" => session[:promo_page]}
  end

  def delete_promotions
    session[:promo_page] = params['per'] if !params['per'].blank?
    params[:page] = 1 if params[:page].blank?

    ProductPromotion.destroy_all(["id IN (?)", params['list']])
    length = params['list'].length
    @product_promotions = ProductPromotion.simple_search(params)
    @product_promotion = @product_promotions.paginate(:page => params['page'], :per_page => session[:promo_page])

    render json: {data: @product_promotion[(session[:promo_page].to_i - length)..(session[:promo_page].to_i)], page: (@product_promotions.count / session[:promo_page].to_f).ceil}
  end

  def stores
    session[:promo_page] = 10 if session[:promo_page].nil?
    @promotion_stores = PromotionStore.joins(:product_store).select("product_stores.store_name, promotion_stores.*").where(:product_promotion_id => session[:product_promotion_id]).paginate(:page => 1, :per_page => session[:promo_page])
    @stores = ProductStore.select("id, store_name")
    @total = @promotion_stores.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotion_stores }
    end
  end

  def stores_per_page
    session[:promo_page] = params['per'] if !params['per'].nil?
    params[:page] = 1 if params[:page].nil?

    params[:product_promotion_id] = session[:product_promotion_id]
    @promotion_stores = PromotionStore.simple_search(params)
    @promotion_store_temp = @promotion_stores.paginate(:page => params['page'], :per_page => session[:promo_page])
    @promotion_store = []
    @promotion_store_temp.each do |promotion_store|
      thru_date = ''
      from_date = ''
      thru_date = promotion_store['thru_date'].strftime("%Y-%m-%d %H:%M:%S:%L") if !promotion_store['thru_date'].blank?
      from_date = promotion_store['from_date'].strftime("%Y-%m-%d %H:%M:%S:%L") if !promotion_store['from_date'].blank?
      item = ActiveSupport::JSON.decode(promotion_store.to_json)
      item['thru_date'] = thru_date
      item['from_date'] = from_date
      @promotion_store.push(item)
    end
    render json: {"data" => @promotion_store, "page" => (@promotion_stores.count / session[:promo_page].to_f).ceil, "per" => session[:promo_page]}
  end

  def update_stores
    store = PromotionStore.find(params["id"])
    store.update_attributes({'thru_date' => params['thru_date'], 'sequence_num' => params['sequence_num']}) if !store.blank?
    render json: params
  end

  def insert_stores
    session[:promo_page] = params['per'] if !params['per'].nil?
    store = PromotionStore.new({"product_store_id" => params['id'], "from_date" => params['from_date'], "thru_date" => params['thru_date'], "sequence_num" => 0, "product_promotion_id" => session[:product_promotion_id]})
    if (store.save)
      render json: {"data" => store, "page" => (PromotionStore.where("product_promotion_id" => session[:product_promotion_id]).count / session[:promo_page].to_f).ceil, "per" => session[:promo_page]}
    else
      render json: {}
    end
  end

  def delete_stores
    session[:promo_page] = params['per'] if !params['per'].blank?
    params[:page] = 1 if params[:page].blank?

    PromotionStore.destroy_all(["id IN (?)", params['list']])
    length = params['list'] ? params['list'].length  : 0
    params[:product_promotion_id] = session[:product_promotion_id]
    @stores = PromotionStore.simple_search(params)
    @store = @stores.paginate(:page => params['page'], :per_page => session[:promo_page])

    render json: {data: PromotionStore.standard_data(@store[(session[:promo_page].to_i - length)..(session[:promo_page].to_i)]), page: (@stores.count / session[:promo_page].to_f).ceil}
  end

end

app/helpers/product_promotions_helper.rb
module ProductPromotionsHelper
end

app/views/product_promotions/_form.html.haml
-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
= form_for @product_promotion ,:html => {:class => "stdform promotion_form"} do |f|
  - if @product_promotion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product_promotion.errors.count, "error")} prohibited this product_promotion from being saved:"
      %ul
        - @product_promotion.errors.full_messages.each do |msg|
          %li= msg
  %div#content-messages.content-messages.errorMessage.notification
    %a.close
  %p
    = f.label :promotion_name, I18n.t('product_promotion.promotion_name')
    %span.field
      = f.text_field :promotion_name
  %p
    = f.label :promotion_text
    %span.field
      = f.text_area :promotion_text,:rows => '5', :cols => '38'
  %p
    = f.label :use_limit_per_customer, I18n.t('product_promotion.use_limit_per_customer')
    %span.field
      = f.number_field :use_limit_per_customer
  %p
    = f.label :use_limit_per_order, I18n.t('product_promotion.use_limit_per_order')
    %span.field
      = f.number_field :use_limit_per_order
  %p
    = f.label :use_limit_per_promotion , I18n.t('product_promotion.use_limit_per_promotion')
    %span.field
      = f.number_field :use_limit_per_promotion

  %p
    = f.label :billback_factor , I18n.t('product_promotion.billback_factor')
    %span.field
      = f.number_field :billback_factor
  %p
    = f.label :override_org_party_id, I18n.t('product_promotion.override_org_party_id')
    %span.field
      = f.number_field :override_org_party_id

  %p
    = f.label :user_entered, I18n.t('product_promotion.user_entered')
    %span.formwrapper
      = f.check_box :user_entered
  %p
    = f.label :require_code, I18n.t('product_promotion.require_code')
    %span.formwrapper
      = f.check_box :require_code
  %p
    = f.label :promotion_show_to_customer, I18n.t('product_promotion.promotion_show_to_customer')
    %span.formwrapper
      = f.check_box :promotion_show_to_customer


  %p.stdformbutton
    = f.submit  I18n.t('common.save') ,:class => 'stdbtn btn_black btn btn-small'
  - unless params[:action] == "new"
    %p
      = f.label :created_by_user_login ,I18n.t('promotion_code.created_by_user_login')
      %span.field
        = '[' + @product_promotion.created_by_user_login.email + '] ON ' + @product_promotion.created_at.to_s(:db)
    %p
      = f.label :last_modified_by_user_login ,I18n.t('promotion_code.last_modified_by_user_login')
      %span.field
        = '[' + @product_promotion.last_modified_by_user_login.email + '] ON ' + @product_promotion.updated_at.to_s(:db)

app/views/product_promotions/_navigation.html.haml
.mainleftinner
  .leftmenu
    %ul
      %li
        %a{"href" => "#", "class" => "dashboard"}
          %span
            %em Dashboard
      %li
        %a{"href" => "#", "class" => "elements"}
          %span
            %em Priorities
      %li.current
        %a{"href" => "#", "class" => "editor menudrop"}
          %span
            %em Products
        %ul{"style" => "display: block;"}
          %li
            %a{"href" => "#"}
              %span
                %em Normal
          %li
            %a{"href" => "/product_promotions"}
              %span
                %em Promotion

      %li
        %a{"href" => "#", "class" => "media"}
          %span
            %em Factories
      %li
        %a{"href" => "#", "class" => "calendar"}
          %span
            %em All Factories
      %li
        %a{"href" => "#", "class" => "buttons"}
          %span
            %em Factory POs
      %li
        %a{"href" => "#", "class" => "error"}
          %span
            %em Customers
      %li
        %a{"href" => "#", "class" => "users"}
          %span
            %em All Customers
      %li
        %a{"href" => "#", "class" => "buttons"}
          %span
            %em Customer SOs
      %li
        %a{"href" => "#", "class" => "widgets"}
          %span
            %em Warehouse
  #togglemenuleft
    %a

app/views/product_promotions/edit.html.haml
%div.contenttitle
  %h2.form
    %span Editing product promotion
= render 'form'

app/views/product_promotions/index.html.haml
-if notice.present?
  .notification.msgsuccess
    %a.close
    %p#notice= notice
%div{"class" => "dataTables_wrapper", "id" => "lists-prdpro"}
  %div.contenttitle
    %h2.general
      %span
        = I18n.t('view.product.promotion.title')
  %div{"id" => "dyntable_length", "class" => "dataTables_length"}
    %a{"href" => "/product_promotions/new"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.new')
    %a{"href" => "#", "id" => "btn-delete"}
      %button{"class" => "stdbtn"}
        = I18n.t('common.delete')
  %div{"class" => "dataTables_filter", "id" => "dyntable_filter"}
    %div{"class" => "search-select"}
      %div
        = I18n.t('active_record.product_promotion.promotion_id')
      %span{"class" => "triangle"}
      %select{"class" => "search-content"}
        %option{"selected" => "selected", "value" => "id"}
          = I18n.t('active_record.product_promotion.promotion_id')
        %option{"value" => "promotion_name"}
          = I18n.t('active_record.product_promotion.promotion_name')
        %option{"value" => "user_entered"}
          = I18n.t('active_record.product_promotion.user_entered')
        %option{"value" => "imported_only"}
          = I18n.t('active_record.product_promotion.import_only')
    %div{"class" => "btn-search"}
    %input{"type" => "text", "id" => "promo-search", "placeholder" => I18n.t('common.type_something')}
  %div.table-wrapper-content
    %table{"class" => "stdtable stdtablecb", "id" => "list-promotions"}
      %thead
        %th.head0.width64
          %input{"type" => "checkbox", "class" => "checkall"}
        %th.head1
          = I18n.t('active_record.product_promotion.promotion_id')
        %th.head0
          = I18n.t('active_record.product_promotion.promotion_name')
        %th.head1
          = I18n.t('active_record.product_promotion.promotion_text')
        %th.head0
          = I18n.t('active_record.product_promotion.require_code')
        %th.head1
          = I18n.t('common.created_at')
      %tbody
        - @product_promotions.each do |promotion|
          %tr{"id" => "proid-"+promotion.id.to_s, "ref" => edit_product_promotion_path(promotion)}
            %td.center
              %span
                %input{"type" => "checkbox"}
            %td.center
              %span
                = promotion.id
            %td
              %span
                = promotion.promotion_name
            %td
              %span
                = promotion.promotion_text
            %td.center
              %span
                = promotion.require_code
            %td.wrap-content.center
              %span
                = promotion.created_at
  %div{"class" => "dataTables_paginate paging_full_numbers"}
    %label{"style" => "float: left"}
      Show
      %select{"size" => 1, "name" => "dyntable_length", "id" => "promotions-per-page"}
        - @nums = [10, 25, 50, 100]
        - @nums.each do |num|
          - if session[:promo_page].to_i == num
            %option{"value" => num, "selected" => "selected"}
              = num
          - if session[:promo_page].to_i != num
            %option{"value" => num}
              = num
    %div{"id" => "dyntable_paginate"}
      - @pages = (@total.to_f / session[:promo_page].to_f).ceil
      - if @pages > 1
        %span{"class" => "first paginate_button", "id" => "dyntable_first"}
          = I18n.t('common.first')
        %span{"class" => "previous paginate_button", "id" => "dyntable_previous"}
          = I18n.t('common.previous')
        %span{"class" => "paginate-body"}
          %span.paginate-body-inner
            - @pages.times do |page|
              - page = page + 1
              - if page == 1
                %span.paginate_active
                  = page
              - if page != 1
                %span.paginate_button
                  = page
        %span{"class" => "next paginate_button", "id" => "dyntable_next"}
          = I18n.t('common.next')
        %span{"class" => "last paginate_button", "id" => "dyntable_last"}
          = I18n.t('common.last')

app/views/product_promotions/new.html.haml
:javascript
  $(document).ready(function(){
    $('ul.maintabmenu').children('li').removeClass('current')
    $('ul.maintabmenu').children('li:nth-child(2)').addClass('current')
  });
%div.contenttitle
  %h2.form
    %span New product promotion
= render 'form'

app/views/product_promotions/show.html.haml
%p#notice= notice

%p
  %b Billback factor:
  = @product_promotion.billback_factor
%p
  %b Override org party:
  = @product_promotion.override_org_party_id
%p
  %b Promotion:
  = @product_promotion.promotion_id
%p
  %b Promotion name:
  = @product_promotion.promotion_name
%p
  %b Promotion show to customer:
  = @product_promotion.promotion_show_to_customer
%p
  %b Promotion text:
  = @product_promotion.promotion_text
%p
  %b Require code:
  = @product_promotion.require_code
%p
  %b Use limit per customer:
  = @product_promotion.use_limit_per_customer
%p
  %b Use limit per order:
  = @product_promotion.use_limit_per_order
%p
  %b Use limit per promotion:
  = @product_promotion.use_limit_per_promotion
%p
  %b User entered:
  = @product_promotion.user_entered

= link_to 'Edit', edit_product_promotion_path(@product_promotion)
\|
= link_to 'Back', product_promotions_path